### ISSUE TITLE
issue with matio

### ISSUE THREAD

**Issue by sandeepangara** [TheLegendAli/DeepLab-Context#8]
Hello @TheLegendAli,

While building caffe in DeepLab I am facing the following issue

ubuntu@ip-172-31-21-77:~/workspace/DeepLab-Context2/build$ cmake ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 7.0
-- Found cuDNN: ver. 4.0.7 found (include: /usr/local/cuda-7.0/include, library: /usr/local/cuda-7.0/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_30
-- OpenCV found (/usr/local/share/OpenCV)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.8.2 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   python
## -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 

-- ******************\* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   6abd64d-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
## --   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
## --   ALLOW_LMDB_NOLOCK :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.54)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   LevelDB           :   Yes (ver. 1.15)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 3.1.0)
## --   CUDA              :   Yes (ver. 7.0)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_30
## --   cuDNN             :   Yes (ver. 4.0.7)

-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.6)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.6)
## --   NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.8.2)

-- Documentaion:
--   Doxygen           :   No
## --   config_file       :   

-- Install:
## --   Install path      :   /home/ubuntu/workspace/DeepLab-Context2/build/install

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/workspace/DeepLab-Context2/build
ubuntu@ip-172-31-21-77:~/workspace/DeepLab-Context2/build$ make -j32 all
[  1%] Running C++/Python protocol buffer compiler on /home/ubuntu/workspace/DeepLab-Context2/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/**/**/include/caffe/proto/caffe.pb.cc.o
Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  2%] [  2%] [  4%] [  4%] [  4%] [  5%] [  6%] [  8%] [  8%] [  8%] [  8%] [  9%] [  9%] [  9%] [  9%] [ 11%] [ 13%] [ 13%] [ 13%] [ 15%] [ 15%] [ 16%] [ 16%] [ 16%] [ 18%] [ 19%] [ 19%] [ 19%] [ 19%] [ 19%] [ 19%] [ 19%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_sgd_solver.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_silence_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_embed_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_reindex_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_loss_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_log_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_threshold_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_spatial_product_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_sigmoid_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_bnll_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_sigmoid_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_inner_product_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_domain_transform_forward_only_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_absval_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_dropout_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_mvn_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_tanh_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_pooling_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_domain_transform_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_lcn_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_pooling_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_lrn_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_eltwise_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_tile_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_filter_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_deconv_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_power_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_reduction_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_concat_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_im2col_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_hdf5_output_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_relu_layer.cu.o
[ 19%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_hdf5_data_layer.cu.o
[ 19%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_euclidean_loss_layer.cu.o
[ 20%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_tanh_layer.cu.o
[ 20%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_sigmoid_cross_entropy_loss_layer.cu.o
[ 20%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_bias_layer.cu.o
[ 22%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_scale_layer.cu.o
[ 22%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_base_data_layer.cu.o
[ 23%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_contrastive_loss_layer.cu.o
[ 23%] [ 23%] [ 25%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_exp_layer.cu.o
[ 25%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_lrn_layer.cu.o
[ 25%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_conv_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_elu_layer.cu.o
[ 26%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_slice_layer.cu.o
[ 26%] [ 27%] [ 27%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_conv_layer.cu.o
[ 27%] [ 29%] [ 29%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_split_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_prelu_layer.cu.o
[ 30%] [ 30%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_relu_layer.cu.o
[ 30%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_layer.cu.o
[ 31%] [ 31%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_batch_norm_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_softmax_layer.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_math_functions.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_im2col.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/util/./cuda_compile_generated_interp.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adadelta_solver.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adagrad_solver.cu.o
[ 31%] [ 33%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_rmsprop_solver.cu.o
[ 33%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_nesterov_solver.cu.o
Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adam_solver.cu.o
Scanning dependencies of target caffe
[ 33%] [ 33%] [ 34%] [ 34%] [ 34%] [ 36%] [ 37%] [ 37%] [ 37%] [ 38%] [ 38%] [ 38%] [ 40%] [ 40%] [ 40%] [ 43%] [ 43%] [ 43%] [ 44%] [ 45%] [ 47%] [ 47%] [ 47%] [ 47%] [ 48%] [ 50%] [ 50%] [ 50%] [ 50%] [ 50%] [ 50%] Building CXX object src/caffe/CMakeFiles/caffe.dir/common.cpp.o
[ 50%] Building CXX object src/caffe/CMakeFiles/caffe.dir/net.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layer_factory.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/data_transformer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mat_write_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/data_reader.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/infogain_loss_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/seg_accuracy_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/batch_norm_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/spp_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/window_data_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/elu_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_relu_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/bias_channel_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/bnll_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hdf5_output_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_conv_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/base_conv_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/contrastive_loss_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/dummy_data_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/inner_product_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/silence_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_pooling_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/multinomial_logistic_loss_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/pooling_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/euclidean_loss_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/tanh_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mat_read_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/softmax_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/adaptive_bias_channel_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/split_layer.cpp.o
[ 50%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/accuracy_layer.cpp.o
[ 50%] [ 51%] [ 51%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hinge_loss_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/mvn_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/reduction_layer.cpp.o
[ 51%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/dropout_layer.cpp.o
[ 52%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/threshold_layer.cpp.o
[ 52%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/scale_layer.cpp.o
[ 54%] [ 54%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_softmax_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/eltwise_layer.cpp.o
[ 54%] [ 55%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_tanh_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/data_layer.cpp.o
[ 55%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/sigmoid_layer.cpp.o
[ 56%] [ 56%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/memory_data_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/conv_layer.cpp.o
[ 56%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/exp_layer.cpp.o
[ 58%] [ 58%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/log_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/spatial_product_layer.cpp.o
[ 58%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_lcn_layer.cpp.o
[ 59%] [ 59%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/batch_reindex_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/embed_layer.cpp.o
[ 61%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/densecrf_layer.cpp.o
[ 61%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/concat_layer.cpp.o
[ 61%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/domain_transform_forward_only_layer.cpp.o
[ 62%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/domain_transform_layer.cpp.o
[ 62%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/im2col_layer.cpp.o
[ 62%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/bias_layer.cpp.o
[ 63%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/filter_layer.cpp.o
[ 63%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/image_data_layer.cpp.o
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/reshape_layer.cpp.o
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/power_layer.cpp.o
[ 65%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/absval_layer.cpp.o
[ 66%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/argmax_layer.cpp.o
[ 66%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_sigmoid_layer.cpp.o
[ 66%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/flatten_layer.cpp.o
[ 68%] [ 68%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/hdf5_data_layer.cpp.o
[ 69%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/cudnn_lrn_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/softmax_loss_layer.cpp.o
[ 69%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/image_seg_data_layer.cpp.o
[ 69%] [ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/prelu_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/slice_layer.cpp.o
[ 70%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/sigmoid_cross_entropy_loss_layer.cpp.o
[ 70%] [ 72%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/relu_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/loss_layer.cpp.o
[ 72%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/deconv_layer.cpp.o
[ 73%] [ 73%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/interp_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/lrn_layer.cpp.o
[ 73%] [ 75%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/base_data_layer.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/tile_layer.cpp.o
[ 75%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/neuron_layer.cpp.o
[ 75%] Building CXX object src/caffe/CMakeFiles/caffe.dir/layers/unique_label_layer.cpp.o
[ 76%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/matio_io.cpp.o
[ 76%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/confusion_matrix.cpp.o
[ 77%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/insert_splits.cpp.o
[ 77%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/permutohedral.cpp.o
[ 77%] [ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/benchmark.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db.cpp.o
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/cudnn.cpp.o
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
[ 80%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o
[ 80%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/blocking_queue.cpp.o
[ 81%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/im2col.cpp.o
[ 81%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_lmdb.cpp.o
[ 81%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_leveldb.cpp.o
[ 83%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/interp.cpp.o
[ 83%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/densecrf_util.cpp.o
[ 84%] [ 84%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/densecrf_pairwise.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o
[ 84%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o
[ 86%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/hdf5.cpp.o
[ 86%] Building CXX object src/caffe/CMakeFiles/caffe.dir/syncedmem.cpp.o
[ 86%] [ 87%] Building CXX object src/caffe/CMakeFiles/caffe.dir/internal_thread.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/layer.cpp.o
[ 87%] Building CXX object src/caffe/CMakeFiles/caffe.dir/parallel.cpp.o
[ 88%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solver.cpp.o
[ 88%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/sgd_solver.cpp.o
[ 88%] [ 90%] [ 90%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adam_solver.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adagrad_solver.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/nesterov_solver.cpp.o
[ 90%] [ 91%] Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/adadelta_solver.cpp.o
Building CXX object src/caffe/CMakeFiles/caffe.dir/solvers/rmsprop_solver.cpp.o
Linking CXX shared library ../../lib/libcaffe.so
[ 91%] Built target caffe
Scanning dependencies of target CMakeCXXCompilerId
Scanning dependencies of target caffe.bin
Scanning dependencies of target convert_imageset
Scanning dependencies of target compute_image_mean
Scanning dependencies of target extract_features
Scanning dependencies of target device_query
Scanning dependencies of target test_net
Scanning dependencies of target finetune_net
Scanning dependencies of target upgrade_net_proto_binary
Scanning dependencies of target convert_mnist_data
Scanning dependencies of target upgrade_solver_proto_text
Scanning dependencies of target convert_mnist_siamese_data
Scanning dependencies of target train_net
Scanning dependencies of target classification
Scanning dependencies of target net_speed_benchmark
Scanning dependencies of target upgrade_net_proto_text
Scanning dependencies of target convert_cifar_data
Scanning dependencies of target pycaffe
[ 91%] [ 91%] Building CXX object tools/CMakeFiles/CMakeCXXCompilerId.dir/CMakeFiles/2.8.12.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
Building CXX object examples/CMakeFiles/convert_mnist_data.dir/mnist/convert_mnist_data.cpp.o
Linking CXX executable CMakeCXXCompilerId
[ 93%] [ 93%] [ 94%] [ 94%] [ 94%] [ 94%] Building CXX object tools/CMakeFiles/device_query.dir/device_query.cpp.o
Building CXX object tools/CMakeFiles/compute_image_mean.dir/compute_image_mean.cpp.o
Building CXX object tools/CMakeFiles/convert_imageset.dir/convert_imageset.cpp.o
Building CXX object examples/CMakeFiles/convert_mnist_siamese_data.dir/siamese/convert_mnist_siamese_data.cpp.o
Building CXX object examples/CMakeFiles/convert_cifar_data.dir/cifar10/convert_cifar_data.cpp.o
[ 95%] [ 95%] Building CXX object tools/CMakeFiles/extract_features.dir/extract_features.cpp.o
[ 97%] [ 97%] [ 97%] [ 97%] [ 98%] [ 98%] Building CXX object tools/CMakeFiles/test_net.dir/test_net.cpp.o
Building CXX object tools/CMakeFiles/finetune_net.dir/finetune_net.cpp.o
Building CXX object tools/CMakeFiles/upgrade_net_proto_binary.dir/upgrade_net_proto_binary.cpp.o
Building CXX object tools/CMakeFiles/caffe.bin.dir/caffe.cpp.o
Building CXX object tools/CMakeFiles/train_net.dir/train_net.cpp.o
Building CXX object tools/CMakeFiles/upgrade_net_proto_text.dir/upgrade_net_proto_text.cpp.o
Building CXX object tools/CMakeFiles/net_speed_benchmark.dir/net_speed_benchmark.cpp.o
Building CXX object tools/CMakeFiles/upgrade_solver_proto_text.dir/upgrade_solver_proto_text.cpp.o
[ 98%] Built target CMakeCXXCompilerId
[100%] [100%] Building CXX object examples/CMakeFiles/classification.dir/cpp_classification/classification.cpp.o
Building CXX object python/CMakeFiles/pycaffe.dir/caffe/_caffe.cpp.o
Linking CXX executable mnist/convert_mnist_data
Linking CXX executable device_query
[100%] Built target device_query
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [examples/mnist/convert_mnist_data] Error 1
make[1]: **\* [examples/CMakeFiles/convert_mnist_data.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
Linking CXX executable siamese/convert_mnist_siamese_data
Linking CXX executable cifar10/convert_cifar_data
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [examples/siamese/convert_mnist_siamese_data] Error 1
make[1]: **\* [examples/CMakeFiles/convert_mnist_siamese_data.dir/all] Error 2
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [examples/cifar10/convert_cifar_data] Error 1
make[1]: **\* [examples/CMakeFiles/convert_cifar_data.dir/all] Error 2
Linking CXX executable compute_image_mean
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/compute_image_mean] Error 1
make[1]: **\* [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
Linking CXX executable convert_imageset
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/convert_imageset] Error 1
make[1]: **\* [tools/CMakeFiles/convert_imageset.dir/all] Error 2
Linking CXX executable test_net
Linking CXX executable train_net
Linking CXX executable net_speed_benchmark
Linking CXX executable upgrade_net_proto_text
[100%] Built target test_net
Linking CXX executable upgrade_solver_proto_text
[100%] Built target train_net
Linking CXX executable finetune_net
[100%] Built target net_speed_benchmark
Linking CXX executable upgrade_net_proto_binary
[100%] Built target finetune_net
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/upgrade_net_proto_text] Error 1
make[1]: **\* [tools/CMakeFiles/upgrade_net_proto_text.dir/all] Error 2
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/upgrade_solver_proto_text] Error 1
make[1]: **\* [tools/CMakeFiles/upgrade_solver_proto_text.dir/all] Error 2
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/upgrade_net_proto_binary] Error 1
make[1]: **\* [tools/CMakeFiles/upgrade_net_proto_binary.dir/all] Error 2
Linking CXX executable extract_features
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/extract_features] Error 1
make[1]: **\* [tools/CMakeFiles/extract_features.dir/all] Error 2
Linking CXX executable cpp_classification/classification
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [examples/cpp_classification/classification] Error 1
make[1]: **\* [examples/CMakeFiles/classification.dir/all] Error 2
Linking CXX executable caffe
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarCreate'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_CreateVer'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarWrite'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_VarFree'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadInfo'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Close'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `Mat_VarReadDataLinear'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to`Mat_Open'
collect2: error: ld returned 1 exit status
make[2]: **\* [tools/caffe] Error 1
make[1]: **\* [tools/CMakeFiles/caffe.bin.dir/all] Error 2
Linking CXX shared library ../lib/_caffe.so
Creating symlink /home/ubuntu/workspace/DeepLab-Context2/python/caffe/_caffe.so -> /home/ubuntu/workspace/DeepLab-Context2/build/lib/_caffe.so
[100%] Built target pycaffe
make: **\* [all] Error 2
ubuntu@ip-172-31-21-77:~/workspace/DeepLab-Context2/build$ 

I have installed matio, Could you please help me.

**Comment by TheLegendAli** [comment]
Not sure what the problem is. Did you trying compiling using regular 'make all' command?

**Comment by abidrahmank** [comment]
Hello @TheLegendAli , I am also facing the same issue. Can you please tell me which version of matio you used?

**Comment by sandeepangara** [comment]
Hello @abidrahmank ,

I am able to build after making the following changes
1) Include the following dependencies in CMakeLists.txt  

find_package(MATIO REQUIRED)
include_directories(${MATIO_INCLUDE_DIR})

2) Include "${MATIO_LIBRARIES}" target_link_libraries in src/caffe/CMakeLists.txt

3) unzip and include the attached file in CMakeScripts directory
[FindMATIO.cmake.zip](https://github.com/TheLegendAli/DeepLab-Context/files/453735/FindMATIO.cmake.zip)

Then build caffe.

**Comment by abidrahmank** [comment]
Thanks @anssandeep . I didn't get the second point. I am not much familiar with cmake. Can you make it a little more clear?

**Comment by sandeepangara** [comment]
Hello @abidrahmank,

Include ${MATIO_LIBRARIES} in target_link_libraries as follows 

target_link_libraries(caffe proto
        ${BLAS_LIBRARIES}
        ${Boost_LIBRARIES}
        ${GFLAGS_LIBRARIES}
        ${GLOG_LIBRARIES}
        ${HDF5_LIBRARIES}
        ${LEVELDB_LIBS}
        ${LMDB_LIBRARIES}
        ${OpenCV_LIBS}
        ${CMAKE_THREAD_LIBS_INIT}
        ${MATIO_LIBRARIES}
)

**Comment by hypercost** [comment]
@anssandeep  I had the same problem. Thanks to your help. It works.

**Comment by bragilee** [comment]
@anssandeep 
Hi, thank you for your solution. I have followed your instructions but I encountered another issue as followings, could anyone help me with it? Do I need to change anything else?

  By not providing "FindMATIO.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MATIO", but
  CMake did not find one.

  Could not find a package configuration file provided by "MATIO" with any of
  the following names:

    MATIOConfig.cmake
    matio-config.cmake

**Comment by makaspacex** [comment]
@anssandeep I had the same problem and it works now. Thanks for your help.

**Comment by Benedetta89** [comment]
I did what you say and I got this error:


CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "FindMATIO.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MATIO", but
  CMake did not find one.

  Could not find a package configuration file provided by "MATIO" with any of
  the following names:

    MATIOConfig.cmake
    matio-config.cmake

  Add the installation prefix of "MATIO" to CMAKE_PREFIX_PATH or set
  "MATIO_DIR" to a directory containing one of the above files.  If "MATIO"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/benedetta/Scrivania/caffe/build/CMakeFiles/CMakeOutput.log".
See also "/home/benedetta/Scrivania/caffe/build/CMakeFiles/CMakeError.log".
Makefile:544: set di istruzioni per l'obiettivo "cmake_check_build_system" non riuscito
make: *** [cmake_check_build_system] Errore 1
 
Where Did I go wrong?

**Comment by askerlee** [comment]
A more elegant (but equivalent) way to @anssandeep 's method:
Append the following to cmake/Dependencies.cmake:
```
find_package(MATIO REQUIRED)
include_directories(${MATIO_INCLUDE_DIR})
list(APPEND Caffe_LINKER_LIBS ${MATIO_LIBRARIES})
```
Then put @anssandeep 's FindMATIO.cmake into cmake/Modules/
Done.

**Comment by yc67** [comment]
Hi, after adding in the above lines "find_package..." and "include_directories...", I'm getting the following error:
<img width="392" alt="2016-12-08 11 53 06" src="https://cloud.githubusercontent.com/assets/23995909/21039167/7fb78312-bda1-11e6-8fb0-e57dd6dc6ada.png">

I tried to directly paste the lines into my Makefile.config.example, and I tried to type them up, but they all generate the same error. Could you please give me some suggestion? Thanks!!

**Comment by askerlee** [comment]
hi @yc67 , were you building with cmake? 
In my environment, Makefile.config is never generated or used.

**Comment by yc67** [comment]
Thank you! I was changing the wrong file. Now I've added "find_package..." and "include_dir..." and "list..." to cmake/dependencies.cmake, and I added the findmatio.cmake file to cmake/Modules/, but I'm still getting the following error:
<img width="665" alt="2016-12-09 12 16 54" src="https://cloud.githubusercontent.com/assets/23995909/21039685/42eed6c0-bda5-11e6-9503-8ce3db77ddce.png">

Should I specify a path to MATIO somewhere? Thanks!

**Comment by askerlee** [comment]
@yc67 have you installed libmatio-dev?

**Comment by yc67** [comment]
Thank you! Problem solved.

**Comment by alimurreza** [comment]
@anssandeep thanks. your solution works for the installation.
@Benedetta89 Just follow what @anssandeep said. There is a subtle thing you might have missed. You have do the the changes in 2 different CMakeLists.txt

change 1:
-------------
Open the CMakeLists.txt in the directory where you have the Makefile.config and add these two lines
find_package(MATIO REQUIRED)
include_directories(${MATIO_INCLUDE_DIR})

change 2:
--------------
Open the CMakeLists.txt inside the src/caffe directory (This is a different one)
now at the end of the target_link_libraries() add the ${MATIO_LIBRARIES} as follows:

target_link_libraries(caffe proto
${BLAS_LIBRARIES}
...
${CMAKE_THREAD_LIBS_INIT}
${MATIO_LIBRARIES})

now do the build procedure using
cmake ..
make all

It should work.

**Comment by feipanir** [comment]
Same problem while building with cmake, thanks very much!

**Comment by ygjwd12345** [comment]
@alimurreza I use cmake to make deeplabv2 ,but I can't find caffe.bin. Can you tell how to find it?
